apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-app
  template: 
    metadata: # Dictionary
      name: example-app-pod
      labels: # Dictionary 
        app: example-app       
    spec:
      containers: # List
        - name: example-app-container          
          image: acrcki.azurecr.io/my_ns/example-app/example-app:v2
          ports:
            - containerPort: 80


    